//to render pages we use get method

const express =  require('express');

const URL = require("../models/url");
const router= express.Router();

router.get("/" , async(req,res,next) =>{
    try {
        if(!req.user) {
            return res.render("home", { urls: null });
        }
        //only urls that are generated by me
        const allurls =  await URL.find({createdBy: req.user._id});
        return res.render("home", {
            urls: allurls,
        });
    } catch (err) {
        next(err);
    }
});

router.get("/signup" , (req,res)=>{
    
    return res.render("signup")
});

router.get("/login", (req,res)=>{
    return res.render("login");
})
module.exports =  router; 